nodeLinker: node-modules

npmScopes:
  ukhomeoffice:
    npmRegistryServer: "https://npm.pkg.github.com"
  asl:
    npmRegistryServer: "https://artifactory.digital.homeoffice.gov.uk/artifactory/api/npm/npm-virtual"
