---
- name: emailer
  recipe: internal-service
  image: quay.io/ukhomeofficedigital/asl-emailer:{{.DRONE_COMMIT_SHA}}
  clients:
    - resolver
  env:
    EMAIL_FROM_ADDRESS: animalscience@digital.homeoffice.gov.uk
    EMAIL_ACCESS_KEY:
      secret: true
      name: asl-dev-ses-2
      key: smtp_username
    EMAIL_SECRET:
      secret: true
      name: asl-dev-ses-2
      key: smtp_password
    EMAIL_REGION: eu-west-1
