#file: noinspection ComposeUnknownKeys,ComposeUnknownValues

kind: pipeline
name: default
type: kubernetes
steps:
  - name: docker build
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_BUILDKIT: 1
    commands:
      - docker build -t asl-toolbox .
  - name: scan-image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    pull: always
    environment:
      IMAGE_NAME: asl-toolbox
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    when:
      event: push
  - name: docker push
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 340268328991.dkr.ecr.eu-west-2.amazonaws.com && echo "Logged into docker";
      - docker tag asl-toolbox 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:$${DRONE_COMMIT_SHA}
      - docker push 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: main

services:
- name: docker
  image: docker:dind
  environment:
    DOCKER_TLS_CERTDIR: ""
