#file: noinspection ComposeUnknownKeys,ComposeUnknownValues

kind: pipeline
name: default
type: kubernetes
steps:
  - name: docker build
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_BUILDKIT: 1
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - docker build -t asl-toolbox .
  - name: scan-image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    pull: always
    environment:
      IMAGE_NAME: asl-toolbox
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    when:
      event: push
  - name: docker push
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-toolbox quay.io/ukhomeofficedigital/asl-toolbox:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-toolbox:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: main

services:
- name: docker
  image: docker:dind
  environment:
    DOCKER_TLS_CERTDIR: ""
