#file: noinspection ComposeUnknownKeys,ComposeUnknownValues

kind: pipeline
name: default
type: kubernetes
steps:
  - name: build
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! "docker stats --no-stream" ]; do n=$(( n + 1 )); sleep 1; done
      - docker build -t asl-toolbox . --no-cache
    when:
      event:
        - push
        - tag

  - name: scan-image
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    pull: always
    environment:
      IMAGE_NAME: asl-toolbox
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    when:
      event:
        - push
        - tag

  - name: docker push latest
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 340268328991.dkr.ecr.eu-west-2.amazonaws.com && echo "Logged into docker";
      - docker tag asl-toolbox 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:$${DRONE_COMMIT_SHA}
      - docker tag asl-toolbox 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:latest
      - docker push 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:$${DRONE_COMMIT_SHA}
      - docker push 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:latest
    when:
      event: push
      branch: main

  - name: docker push tag
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 340268328991.dkr.ecr.eu-west-2.amazonaws.com && echo "Logged into docker";
      - docker tag asl-toolbox 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:$${DRONE_TAG}
      - docker push 340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/toolbox:$${DRONE_TAG}
    when:
      event: tag

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
