---
- name: permissions
  recipe: internal-service
  clients:
    - public-api
    - internal-api
    - public-ui
    - internal-ui
    - workflow
  image: quay.io/ukhomeofficedigital/asl-permissions:{{config.versions.asl-permissions}}
  healthcheck: /healthcheck
  replicas: 1
  memory:
    requests: 32Mi
    limit: 256Mi
  cpu:
    requests: 50m
    limit: 400m
  keys: tls-keys
  env:
    KEYCLOAK_REALM: Asl-dev
    KEYCLOAK_URL: {{config.urls.keycloak}}
    KEYCLOAK_CLIENT: asl-dev-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-preprod-auth
      key: secret
    DATABASE_HOST:
      secret: true
      name: asl-preprod-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asl-preprod-rds
      key: db_name
    DATABASE_USERNAME: permissions
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: permissions
    DATABASE_PORT:
      secret: true
      name: asl-preprod-rds
      key: port
    CACHE_TTL: 2 minutes
    REDIS_HOST: permissions-redis
    REDIS_PASSWORD:
      secret: true
      name: asl-preprod-redis
      key: pass

- name: permissions-redis
  recipe: redis
  clients: permissions
  passwordName: asl-preprod-redis
  passwordKey: pass
  memory:
    requests: 16Mi
    limit: 64Mi
  cpu:
    requests: 20m
    limit: 100m

- name: permissions
  recipe: autoscaler
  min: 1
  max: 3
