---
- name: public-search
  recipe: internal-service
  clients:
    - public-api
  image: quay.io/ukhomeofficedigital/asl-search:{{config.versions.asl-search}}
  healthcheck: /healthcheck
  replicas: 1
  memory:
    requests: 32Mi
    limit: 512Mi
  cpu:
    requests: 50m
    limit: 400m
  keys: tls-keys
  env:
    AWS_ES_ENDPOINT:
      secret: true
      name: asl-elasticsearch
      key: ENDPOINT
    AWS_ES_KEY:
      secret: true
      name: asl-elasticsearch
      key: AWS_ACCESS_KEY_ID
    AWS_ES_SECRET:
      secret: true
      name: asl-elasticsearch
      key: AWS_SECRET_ACCESS_KEY
    KEYCLOAK_REALM: Asl-dev
    KEYCLOAK_URL: {{config.urls.keycloak}}
    KEYCLOAK_CLIENT: asl-dev-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-preprod-auth
      key: secret
    DATABASE_HOST:
      secret: true
      name: asl-preprod-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asl-preprod-rds
      key: db_name
    DATABASE_USERNAME: search
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: search
    DATABASE_PORT:
      secret: true
      name: asl-preprod-rds
      key: port
  nginx:
    ADD_NGINX_SERVER_CFG: add_header Cache-Control private;
