---
- name: pdf-generator
  recipe: internal-service
  clients:
    - internal-ui
    - public-ui
  image: quay.io/ukhomeofficedigital/html-pdf-converter:{{config.versions.pdf-generator}}
  memory:
    requests: 32Mi
    limit: 512Mi
  cpu:
    requests: 50m
    limit: 400m
  replicas: 1
  keys: tls-keys
  env:
    BODY_SIZE_LIMIT: 50mb
  nginx:
    CLIENT_MAX_BODY_SIZE: "'50'"
