
kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:12
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm ci
  - name: test
    image: node:12
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm test
  - name: audit
    image: node:12
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npx @lennym/ciaudit --retries 5
  - name: docker build
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_BUILDKIT: 1
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build --secret id=username,env=NPM_AUTH_USERNAME --secret id=token,env=NPM_AUTH_TOKEN -t asl-data-exports .
  - name: docker push
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-data-exports quay.io/ukhomeofficedigital/asl-data-exports:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-data-exports:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: main
  - name: update manifest
    image: quay.io/ukhomeofficedigital/asl-deploy-bot:latest
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: github_access_token
    commands:
      - update
        --repo ukhomeoffice/asl-deployments
        --token $${GITHUB_ACCESS_TOKEN}
        --file versions.yml
        --service asl-data-exports
        --version $${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: main

services:
- name: docker
  image: docker:dind
  environment:
    DOCKER_TLS_CERTDIR: ""
