apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.SERVICE_NAME}}-redis
    service: {{.SERVICE_NAME}}-redis
  name: {{.SERVICE_NAME}}-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: {{.SERVICE_NAME}}-redis
