name: 'Publish - npm'
on:
  pull_request:
    types: [ closed ]

permissions:
  packages: write
  contents: write

jobs:
  publish:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/publish-npm.yml@v1
    permissions:
      packages: write
      contents: write
    secrets: inherit
