name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/test-npm.yml@v1
    secrets: inherit
  env: 
    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
