pipeline:
  test:
    image: node:8
    commands:
      - npm install
      - npm test
    when:
      branch: master
      event: push

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t asl .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl quay.io/ukhomeofficedigital/asl:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push
