---
- name: public-ui
  recipe: webapp
  url: public-ui.notprod.asl.homeoffice.gov.uk
  image: quay.io/ukhomeofficedigital/asl:{{.DRONE_COMMIT_SHA}}
  env:
    REDIS_HOST: public-ui-redis
    REDIS_PASSWORD:
      secret: true
      name: asl-dev-redis
      key: pass
    SESSION_SECRET:
      secret: true
      name: asl-dev-session
      key: secret
    KEYCLOAK_REALM: Asl-dev
    KEYCLOAK_URL: https://sso-dev.notprod.homeoffice.gov.uk/auth
    KEYCLOAK_CLIENT: asl-dev-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-dev-auth
      key: secret
    API_URL: https://public-api.notprod.asl.homeoffice.gov.uk
    PDF_SERVICE: https://pdf-generator.notprod.asl.homeoffice.gov.uk/convert

- name: pdf-generator
  recipe: webapp
  url: pdf-generator.notprod.asl.homeoffice.gov.uk
  image: quay.io/ukhomeofficedigital/html-pdf-converter:216c4dd30064b3a92ce5ca6ea429f47256069dca
  env:
    APP_PORT: '"8080"'

- name: public-ui-redis
  recipe: redis
  clients: public-ui
  passwordName: asl-dev-redis
  passwordKey: pass
