---
- name: public-ui
  recipe: webapp
  url: public-ui.preprod.asl.homeoffice.gov.uk
  image: quay.io/ukhomeofficedigital/asl:{{.DRONE_COMMIT_SHA}}
  env:
    REDIS_HOST: public-ui-redis
    REDIS_PASSWORD:
      secret: true
      name: asl-preprod-redis
      key: pass
    SESSION_SECRET:
      secret: true
      name: asl-preprod-session
      key: secret
    KEYCLOAK_REALM: Asl-dev
    KEYCLOAK_URL: https://sso-dev.notprod.homeoffice.gov.uk/auth
    KEYCLOAK_CLIENT: asl-dev-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-preprod-auth
      key: secret
    API_URL: https://public-api.preprod.asl.homeoffice.gov.uk

- name: public-ui-redis
  recipe: redis
  clients: public-ui
  passwordName: asl-preprod-redis
  passwordKey: pass
