---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asl-{{.DEPLOY_TO}}-{{.SERVICE_NAME}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: asl-{{.DEPLOY_TO}}-{{.SERVICE_NAME}}
        service: asl-{{.DEPLOY_TO}}-{{.SERVICE_NAME}}
    spec:
      containers:
        - name: asl-{{.DEPLOY_TO}}-{{.SERVICE_NAME}}
          image: quay.io/ukhomeofficedigital/asl-inspector-api:{{.DRONE_COMMIT_SHA}}
          imagePullPolicy: Always
          env:
            - name: KEYCLOAK_REALM
              value: Asl-dev
            - name: KEYCLOAK_URL
              value: https://sso-dev.notprod.homeoffice.gov.uk/auth
            - name: KEYCLOAK_CLIENT
              value: asl-dev-connect
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: asl-dev-auth
                  key: secret
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: asl-dev-rds
                  key: endpoint
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: asl-dev-rds
                  key: db_name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: asl-dev-rds
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: asl-dev-rds
                  key: password
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: asl-dev-rds
                  key: port
          resources:
            limits:
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
        - name: nginx-proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy-govuk:v3
          env:
            - name: PROXY_SERVICE_HOST
              value: 127.0.0.1
            - name: PROXY_SERVICE_PORT
              value: "8080"
            - name: ENABLE_UUID_PARAM
              value: "FALSE"
            - name: NAXSI_USE_DEFAULT_RULES
              value: "FALSE"
            - name: PORT_IN_HOST_HEADER
              value: "FALSE"
            - name: ERROR_REDIRECT_CODES
              value: ""
            - name: ADD_NGINX_SERVER_CFG
              value: |
                add_header Cache-Control private;
                add_header X-Frame-Options "SAMEORIGIN" always;
                add_header X-Content-Type-Options "nosniff" always;
                add_header X-XSS-Protection "1; mode=block" always;
          ports:
            - containerPort: 10443
          securityContext:
            runAsNonRoot: true
