---
- name: notifications
  recipe: internal-service
  clients:
    - workflow
  image: quay.io/ukhomeofficedigital/asl-notifications:{{config.versions.asl-notifications}}
  healthcheck: /healthcheck
  memory:
    requests: 128Mi
    limit: 512Mi
  cpu:
    requests: 100m
    limit: 400m
  replicas: 2
  keys: tls-keys
  env:
    EMAILER_SERVICE: {{config.urls.emailer}}
    PUBLIC_UI: {{config.urls.public-ui}}
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: notifications
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: notifications
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port
    NODE_TLS_REJECT_UNAUTHORIZED: "'0'"

- name: notifications
  recipe: autoscaler
  min: 2
  max: 4

- name: notifications-nightly
  recipe: cronjob
  image: quay.io/ukhomeofficedigital/asl-notifications:{{config.versions.asl-notifications}}
  schedule: '0 0 * * *'
  command: npm run job -- ./jobs/nightly-jobs
  memory:
    requests: 32Mi
    limit: 256Mi
  cpu:
    requests: 100m
    limit: 400m
  env:
    EMAILER_SERVICE: {{config.urls.emailer}}
    PUBLIC_UI: {{config.urls.public-ui}}
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: notifications
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: notifications
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port

- name: notify-rop-reminders-year-end
  recipe: cronjob
  image: quay.io/ukhomeofficedigital/asl-notifications:{{config.versions.asl-notifications}}
  schedule: '0 0 31 12 *'
  command: npm run job -- ./jobs/rop-reminder-notice-active
  memory:
    requests: 32Mi
    limit: 256Mi
  cpu:
    requests: 100m
    limit: 400m
  env:
    EMAILER_SERVICE: {{config.urls.emailer}}
    PUBLIC_UI: {{config.urls.public-ui}}
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: notifications
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: notifications
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port

- name: poll-notifications
  recipe: cronjob
  image: quay.io/ukhomeofficedigital/asl-notifications:{{config.versions.asl-notifications}}
  schedule: '*/5 * * * *'
  command: npm run job -- ./jobs/poll-notifications
  memory:
    requests: 32Mi
    limit: 256Mi
  cpu:
    requests: 100m
    limit: 400m
  env:
    EMAILER_SERVICE: {{config.urls.emailer}}
    PUBLIC_UI: {{config.urls.public-ui}}
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: notifications
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: notifications
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port
    NODE_TLS_REJECT_UNAUTHORIZED: "'0'"
