---
- name: resolver
  recipe: worker
  image: quay.io/ukhomeofficedigital/asl-resolver:{{config.versions.asl-resolver}}
  replicas: 2
  memory:
    requests: 256Mi
    limit: 1024Mi
  cpu:
    requests: 200m
    limit: 1000m
  env:
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: resolver
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: resolver
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port
    SQS_REGION: eu-west-2
    SQS_ACCESS_KEY:
      secret: true
      name: asl-changerequests-sqs
      key: access_key_id
    SQS_SECRET:
      secret: true
      name: asl-changerequests-sqs
      key: secret_access_key
    SQS_URL:
      secret: true
      name: asl-changerequests-sqs
      key: sqs_queue_url
    JWT_SECRET:
      secret: true
      name: asl-prod-jwt
      key: token
    S3_REGION: eu-west-2
    S3_ACCESS_KEY:
      secret: true
      name: asl-prod-transfer-s3
      key: access_key_id
    S3_SECRET:
      secret: true
      name: asl-prod-transfer-s3
      key: secret_access_key
    S3_BUCKET:
      secret: true
      name: asl-prod-transfer-s3
      key: name
    S3_KMS_KEY_ID:
      secret: true
      name: asl-prod-transfer-s3
      key: kms_key_id
    TRANSPORT_KEY:
      secret: true
      name: s3-encryption
      key: key
    TRANSPORT_IV:
      secret: true
      name: s3-encryption
      key: iv
    EMAILER_SERVICE: {{config.urls.emailer}}
    REGISTER_SERVICE: {{config.urls.public-ui}}
    KEYCLOAK_REALM: asl
    KEYCLOAK_URL: {{config.urls.keycloak}}
    KEYCLOAK_CLIENT: asl-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-prod-auth
      key: secret
    KEYCLOAK_USERNAME:
      secret: true
      name: keycloak-admin
      key: username
    KEYCLOAK_PASSWORD:
      secret: true
      name: keycloak-admin
      key: password
    NODE_TLS_REJECT_UNAUTHORIZED: "'0'"

- name: resolver
  recipe: autoscaler
  min: 2
  max: 4

- name: expire-projects
  recipe: cronjob
  image: quay.io/ukhomeofficedigital/asl-resolver:{{config.versions.asl-resolver}}
  schedule: '0 0 * * *'
  command: npm run task -- ./tasks/expire
  memory:
    requests: 32Mi
    limit: 256Mi
  cpu:
    requests: 100m
    limit: 400m
  env:
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: resolver
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: resolver
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port

- name: reset-billing-details
  recipe: cronjob
  image: quay.io/ukhomeofficedigital/asl-resolver:{{config.versions.asl-resolver}}
  schedule: '15 0 31 12 *'
  command: npm run task -- ./tasks/reset-billing
  memory:
    requests: 32Mi
    limit: 256Mi
  cpu:
    requests: 100m
    limit: 400m
  env:
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: resolver
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: resolver
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port
