---
- name: public-api
  recipe: internal-service
  image: quay.io/ukhomeofficedigital/asl-public-api:{{config.versions.asl-public-api}}
  healthcheck: /healthcheck
  replicas: 2
  memory:
    requests: 256Mi
    limit: 1024Mi
  cpu:
    requests: 400m
    limit: 1000m
  keys: tls-keys
  clients:
    - public-ui
    - internal-api
    - workflow
  env:
    PERMISSIONS_SERVICE: {{config.urls.permissions}}
    WORKFLOW_SERVICE: {{config.urls.workflow}}
    SEARCH_SERVICE: {{config.urls.public-search}}
    KEYCLOAK_REALM: asl
    KEYCLOAK_URL: {{config.urls.keycloak}}
    KEYCLOAK_CLIENT: asl-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-prod-auth
      key: secret
    KEYCLOAK_USERNAME:
      secret: true
      name: keycloak-admin
      key: username
    KEYCLOAK_PASSWORD:
      secret: true
      name: keycloak-admin
      key: password
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: publicapi
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: publicapi
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port
    REDIS_HOST: public-api-redis
    REDIS_PASSWORD:
      secret: true
      name: asl-prod-redis
      key: pass
    RATE_LIMIT_TOTAL: '"10000"'
    NODE_TLS_REJECT_UNAUTHORIZED: "'0'"
    BODY_SIZE_LIMIT: 50mb
  nginx:
    ADD_NGINX_SERVER_CFG: add_header Cache-Control private;
    CLIENT_MAX_BODY_SIZE: "'50'"

- name: public-api-redis
  recipe: redis
  clients: public-api
  passwordName: asl-prod-redis
  passwordKey: pass
  memory:
    requests: 16Mi
    limit: 64Mi
  cpu:
    requests: 20m
    limit: 100m

- name: public-api
  recipe: autoscaler
  min: 2
  max: 4
