---
- name: metrics
  recipe: internal-service
  clients:
    - internal-ui
    - internal-api
    - data-exports
  image: quay.io/ukhomeofficedigital/asl-metrics:{{config.versions.asl-metrics}}
  healthcheck: /healthcheck
  replicas: 1
  memory:
    requests: 256Mi
    limit: 1024Mi
  cpu:
    requests: 400m
    limit: 800m
  keys: tls-keys
  env:
    KEYCLOAK_REALM: asl
    KEYCLOAK_URL: {{config.urls.keycloak}}
    KEYCLOAK_CLIENT: asl-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-prod-auth
      key: secret
    DATABASE_HOST:
      secret: true
      name: aslworkflow-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: aslworkflow-rds
      key: default_db
    DATABASE_USERNAME: metricsworkflow
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: metricsworkflow
    DATABASE_PORT:
      secret: true
      name: aslworkflow-rds
      key: port
    ASL_DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    ASL_DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: db_name
    ASL_DATABASE_USERNAME: metrics
    ASL_DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: metrics
    ASL_DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port
    NODE_TLS_REJECT_UNAUTHORIZED: "'0'"
    FLOW_URL: {{config.urls.workflow}}/flow

- name: metrics
  recipe: autoscaler
  min: 2
  max: 4
