---
- name: permissions
  recipe: internal-service
  clients:
    - public-api
    - internal-api
    - public-ui
    - internal-ui
    - workflow
  image: quay.io/ukhomeofficedigital/asl-permissions:{{config.versions.asl-permissions}}
  healthcheck: /healthcheck
  memory:
    requests: 128Mi
    limit: 512Mi
  cpu:
    requests: 200m
    limit: 1000m
  replicas: 2
  keys: tls-keys
  env:
    KEYCLOAK_REALM: asl
    KEYCLOAK_URL: {{config.urls.keycloak}}
    KEYCLOAK_CLIENT: asl-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-prod-auth
      key: secret
    DATABASE_HOST:
      secret: true
      name: asldata-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asldata-rds
      key: default_db
    DATABASE_USERNAME: permissions
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: permissions
    DATABASE_PORT:
      secret: true
      name: asldata-rds
      key: port
    CACHE_TTL: 2 minutes
    REDIS_HOST: permissions-redis
    REDIS_PASSWORD:
      secret: true
      name: asl-prod-redis
      key: pass

- name: permissions-redis
  recipe: redis
  clients: permissions
  passwordName: asl-prod-redis
  passwordKey: pass
  memory:
    requests: 32Mi
    limit: 64Mi
  cpu:
    requests: 20m
    limit: 100m

- name: permissions
  recipe: autoscaler
  min: 2
  max: 4
