apiVersion: v1
kind: Pod
metadata:
  name: mysql-admin
spec:
  securityContext:
    runAsUser: 1111
    fsGroup: 1111
  containers:
    - name: tools
      image: quay.io/ukhomeofficedigital/srrs-tooling:latest
      resources:
        limits:
          cpu: 400m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1111
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: aslmysqlread-rds
              key: endpoint
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: aslmysqlread-rds
              key: port
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: aslmysqlread-rds
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: aslmysqlread-rds
              key: password
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: aslmysqlread-rds
              key: default_db
      ports:
        - containerPort: 8080
          name: toolset
