apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
    - name: tools
      image: quay.io/ukhomeofficedigital/postgres-client:latest
      resources:
        limits:
          cpu: 50m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 70
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: asldata-rds
              key: endpoint
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: asldata-rds
              key: port
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: asldata-rds
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: asldata-rds
              key: password
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: asldata-rds
              key: default_db
        - name: WORKFLOW_HOST
          valueFrom:
            secretKeyRef:
              name: aslworkflow-rds
              key: endpoint
        - name: WORKFLOW_PORT
          valueFrom:
            secretKeyRef:
              name: aslworkflow-rds
              key: port
        - name: WORKFLOW_USERNAME
          valueFrom:
            secretKeyRef:
              name: aslworkflow-rds
              key: username
        - name: WORKFLOW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aslworkflow-rds
              key: password
        - name: WORKFLOW_DATABASE
          valueFrom:
            secretKeyRef:
              name: aslworkflow-rds
              key: default_db
        - name: PASSWORD_PUBLICAPI
          valueFrom:
            secretKeyRef:
              name: dbpasswords
              key: publicapi
        - name: PASSWORD_INTERNALAPI
          valueFrom:
            secretKeyRef:
              name: dbpasswords
              key: internalapi
        - name: PASSWORD_WORKFLOW
          valueFrom:
            secretKeyRef:
              name: dbpasswords
              key: workflow
        - name: PASSWORD_RESOLVER
          valueFrom:
            secretKeyRef:
              name: dbpasswords
              key: resolver
        - name: PASSWORD_PERMISSIONS
          valueFrom:
            secretKeyRef:
              name: dbpasswords
              key: permissions
        - name: PASSWORD_NOTIFICATIONS
          valueFrom:
            secretKeyRef:
              name: dbpasswords
              key: notifications
      ports:
        - containerPort: 8080
          name: toolset
