kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:18
    environment:
      ART_AUTH_USERNAME:
        from_secret: art_auth_username
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm ci
  - name: test
    image: node:18
    environment:
      ART_AUTH_USERNAME:
        from_secret: art_auth_username
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm test
  - name: publish
    image: node:18
    environment:
      ART_AUTH_USERNAME:
        from_secret: art_auth_username
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm publish
    when:
      event:
        - tag
