pipeline:

  test:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npm ci
      - npm test
    when:
      event:
        - push
        - pull_request
        - tag

  audit:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npx @lennym/ciaudit --retries 5
    when:
      event:
        - push
        - pull_request
        - tag
  compile:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npm run build --production
    when:
      event:
        - push
        - pull_request
        - tag

  publish:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: tag

matrix:
  NPM_AUTH_USERNAME:
    - asl
