module.exports = [
  'Mice (Mus musculus)',
  'Rats (Rattus norvegicus)',
  'Guinea pigs (Cavia porcellus)',
  'Hamsters (Syrian) (Mesocricetus auratus)',
  'Hamsters (Chinese) (Cricetulus griseus)',
  'Mongolian gerbils (Meriones unguiculatus)',
  'Other rodents (other Rodentia)',
  'Rabbits (Oryctolagus cuniculus)',
  'Cats (Felis catus)',
  'Beagles (Canis lupus familiaris)',
  'Other dogs (other Canis)',
  'Ferrets (Mustela putorius furo)',
  'Horses, donkeys and cross-breeds (Equidae)',
  'Pigs (Sus scrofa domesticus)',
  'Goats (Capra aegagrus hircus)',
  'Sheep (Ovis aries)',
  'Cattle (Bos primigenius)',
  'Prosimians (Prosimia)',
  'Marmosets and tamarins (eg. Callithrix jacchus)',
  'Cynomolgus monkeys (Macaca fascicularis)',
  'Rhesus monkeys (Macaca mulatta)',
  'Vervets Chlorocebus spp. (usually either pygerythrus or sabaeus)',
  'Baboons (Papio spp.)',
  'Squirrel monkeys (eg. Saimiri sciureus)',
  'Other species of Old World Monkeys (Cercopithecoidea)',
  'Other species of New World Monkeys (Ceboidea)',
  'Apes (Hominoidea)',
  'Domestic fowl (Gallus gallus domesticus)',
  'Quails (Coturnix coturnix)',
  'Other birds (other Aves)',
  'Reptiles (Reptilia)',
  'Frog (Rana temporaria - common frog and Rana pipiens - Northern leopard frog)',
  'Xenopus (Xenopus laevis and Xenopus tropicalis)',
  'Other amphibians (other Amphibia)',
  'Zebra fish (Danio rerio)',
  'Other fish (other Pisces)',
  'Cephalopods (Cephalopoda)',
  'Other'
];
