module.exports = [
  'Mice (Mus musculus)',
  'Rats (Rattus norvegicus)',
  'Guinea pigs (Cavia porcellus)',
  'Hamsters (Syrian) (Mesocricetus auratus)',
  'Hamsters (Chinese) (Cricetulus griseus)',
  'Mongolian gerbils (Meriones unguiculatus)',
  'Other rodents (other Rodentia)',
  'Rabbits (Oryctolagus cuniculus)',
  'Ferrets (Mustela putorius furo)',
  'Pigs (Sus scrofa domesticus)',
  'Goats (Capra aegagrus hircus)',
  'Sheep (Ovis aries)',
  'Cattle (Bos primigenius)',
  'Reptiles (Reptilia)',
  'Common and Northern leopard frogs (Rana temporaria and Rana pipiens)',
  'African and Western clawed frogs (Xenopus laevis and Xenopus tropicalis)',
  'Other amphibians (other Amphibia)',
  'Zebra fish (Danio rerio)',
  'Other fish (other Pisces)',
  'Cephalopods (Cephalopoda)',
  'Domestic fowl (Gallus gallus domesticus)',
  'Quails (Coturnix coturnix)',
  'Other birds (other Aves)',
  'Beagles (Canis lupus familiaris)',
  'Other dogs (other Canis)',
  'Cats (Felis catus)',
  'Horses, donkeys and cross-breeds (Equidae)',
  'Prosimians (Prosimia)',
  'Marmosets and tamarins (eg. Callithrix jacchus)',
  'Cynomolgus monkeys (Macaca fascicularis)',
  'Rhesus monkeys (Macaca mulatta)',
  'Vervets (Chlorocebus - usually either pygerythrus or sabaeus)',
  'Baboons (Papio spp.)',
  'Squirrel monkeys (for example, Saimiri sciureus)',
  'Other Old World monkeys (Cercopithecoidea)',
  'Other New World monkeys (Ceboidea)',
  'Apes (Hominoidea)',
  'Other'
];
