module.exports = [
  'Mice (Mus musculus)',
  'Rats (Rattus norvegicus)',
  'Guinea-Pigs (Cavia porcellus)',
  'Hamsters (Syrian) (Mesocricetus auratus)',
  'Hamsters (chinese) (Cricetulus griseus)',
  'Mongolian gerbil (Meriones unguiculatus)',
  'Other Rodents (other Rodentia)',
  'Rabbits (Oryctolagus cuniculus)',
  'Cats (Felis catus)',
  'Beagles (Canis lupus familiaris)',
  'Other dogs (Other Canis)',
  'Ferrets (Mustela putorius furo)',
  'Other carnivores (other Carnivora)',
  'Horses, donkeys & cross-breeds (Equidae)',
  'Pigs (Sus scrofa domesticus)',
  'Goats (Capra aegagrus hircus)',
  'Sheep (Ovis aries)',
  'Cattle (Bos primigenius)',
  'Prosimians (Prosimia)',
  'Marmoset and tamarins (eg. Callithrix jacchus)',
  'Cynomolgus monkey (Macaca fascicularis)',
  'Rhesus monkey (Macaca mulatta)',
  'Vervets Chlorocebus spp. (usually either pygerythrus or sabaeus)',
  'Baboons (Papio spp.)',
  'Squirrel monkey (eg. Saimiri sciureus)',
  'Other species of Old World Monkeys (Cercopithecoidea)',
  'Other species of New World Monkeys (Ceboidea)',
  'Apes (Hominoidea)',
  'Other Mammals (other Mammalia)',
  'Domestic fowl (Gallus gallus domesticus)',
  'Quail (Coturnix coturnix)',
  'Other birds (other Aves)',
  'Reptiles (Reptilia)',
  'Rana (Rana temporaria and Rana pipiens)',
  'Xenopus (Xenopus laevis and Xenopus tropicalis)',
  'Other Amphibians (other Amphibia)',
  'Zebra fish (Danio rerio)',
  'Other Fish (other Pisces)',
  'Cephalopods (Cephalopoda)'
];
