apiVersion: v1
kind: Service
metadata:
  name: asl-{{.DEPLOY_TARGET}}-{{.SERVICE_NAME}}
  labels:
    name: asl-{{.DEPLOY_TARGET}}-{{.SERVICE_NAME}}
    role: service
spec:
  ports:
  - name: http
    port: 10080
  - name: https
    port: 10443
  selector:
    name: asl-{{.DEPLOY_TARGET}}-{{.SERVICE_NAME}}
