---

kind: pipeline
name: <MODULE_NAME>
type: kubernetes

clone:
  disable: true

steps:
  - name: clone
    image: node:22.14.0
    commands:
      - git clone $DRONE_REMOTE_URL .
  - name: changeset
    image: node:22.14.0
    environment:
      TARGET_BRANCH: "${DRONE_TARGET_BRANCH}"
      SOURCE_COMMIT: "${DRONE_COMMIT}"
      BUILD_EVENT: "${DRONE_BUILD_EVENT}"
      SKIP_STATUS: 78
      MODULES: packages/<MODULE_NAME>
    commands:
      - git config advice.detachedHead false
      - git checkout $DRONE_COMMIT
      - node ./ci/changeset.js --modules $MODULES
      - git checkout $DRONE_TARGET_BRANCH
      - git merge $DRONE_COMMIT
      - echo "$(node ./ci/modulepaths.js $MODULES)" > .module-paths
  - name: install
    image: node:22.14.0
    environment:
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm ci --workspace <MODULE_NAME>
  - name: test
    image: node:22.14.0
    environment:
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm run test --workspace <MODULE_NAME>
  - name: audit
    image: node:22.14.0
    environment:
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm audit --workspace=<MODULE_NAME> --audit-level=critical --omit=dev
  - name: docker build
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_BUILDKIT: 1
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - docker build -f ./packages/<MODULE_NAME>/Dockerfile --build-arg MODULE_PATHS="$(cat .module-paths)" --secret id=token,env=ART_AUTH_TOKEN --secret id=github_token,env=GITHUB_AUTH_TOKEN -t <MODULE_NAME> .
  - name: scan-image
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: <MODULE_NAME>
      ALLOW_CVE_LIST_FILE: packages/<MODULE_NAME>/cve-exceptions.txt
  - name: docker push
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
      DOCKER_PASSWORD:
        from_secret: quay_password
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag <MODULE_NAME> quay.io/ukhomeofficedigital/<MODULE_NAME>:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/<MODULE_NAME>:$${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - main
  - name: update manifest
    image: quay.io/ukhomeofficedigital/asl-deploy-bot:latest
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: github_access_token
    commands:
      - update
        --repo ukhomeoffice/asl-deployments
        --token $${GITHUB_ACCESS_TOKEN}
        --file versions.yml
        --service <MODULE_NAME>
        --version $${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - main

services:
- name: docker
  image: docker:dind
  environment:
    DOCKER_TLS_CERTDIR: ""
