pipeline:

  test:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm install
      - npm test
    when:
      event: [push, pull_request, tag]

  build:
    image: node:8
    commands:
      - npm run build
    when:
      event: [push, pull_request, tag]
    secrets:
      - npm_auth_token

  functionaltest:
    image: node:8
    commands:
      - npm run test:functional -- --host selenium
    when:
      event: [push, pull_request, tag]
    secrets:
      - npm_auth_token

  publish:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: tag

matrix:
  NPM_AUTH_USERNAME:
    - asl


services:
  selenium:
    image: selenium/standalone-chrome
    when:
      event: [push, pull_request, tag]
