---
- name: emailer
  recipe: webapp
  url: emailer.dev.asl.homeoffice.gov.uk
  image: quay.io/ukhomeofficedigital/asl-stub:{{config.versions.asl-stub}}
  replicas: 1
  memory:
    requests: 32Mi
    limit: 256Mi
  cpu:
    requests: 20m
    limit: 200m
  env:
    DATABASE_HOST:
      secret: true
      name: asl-dev-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asl-dev-rds
      key: db_name
    DATABASE_USERNAME: notifications
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: notifications
    DATABASE_PORT:
      secret: true
      name: asl-dev-rds
      key: port
