---
- name: 0-workflow-migration.job
  recipe: job
  image: quay.io/ukhomeofficedigital/asl-workflow:{{config.versions.asl-workflow}}
  memory:
    requests: 64Mi
    limit: 256Mi
  cpu:
    requests: 50m
    limit: 400m
  command: npm run migrate
  env:
    DATABASE_HOST:
      secret: true
      name: asl-dev-workflow-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asl-dev-workflow-rds
      key: default_db
    DATABASE_USERNAME:
      secret: true
      name: asl-dev-workflow-rds
      key: username
    DATABASE_PASSWORD:
      secret: true
      name: asl-dev-workflow-rds
      key: password
    DATABASE_PORT:
      secret: true
      name: asl-dev-workflow-rds
      key: port
