---
- name: 2-rebuild-search-index.job
  recipe: job
  image: quay.io/ukhomeofficedigital/asl-search:{{config.versions.asl-search}}
  command: bin/indexer --reset
  memory:
    requests: 32Mi
    limit: 512Mi
  cpu:
    requests: 50m
    limit: 400m
  env:
    AWS_ES_ENDPOINT:
      secret: true
      name: asl-elasticsearch
      key: ENDPOINT
    AWS_ES_KEY:
      secret: true
      name: asl-elasticsearch
      key: AWS_ACCESS_KEY_ID
    AWS_ES_SECRET:
      secret: true
      name: asl-elasticsearch
      key: AWS_SECRET_ACCESS_KEY
    DATABASE_HOST:
      secret: true
      name: asl-dev-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asl-dev-rds
      key: db_name
    DATABASE_USERNAME: search
    DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: search
    DATABASE_PORT:
      secret: true
      name: asl-dev-rds
      key: port
    TASK_DATABASE_HOST:
      secret: true
      name: asl-dev-workflow-rds
      key: endpoint
    TASK_DATABASE_NAME:
      secret: true
      name: asl-dev-workflow-rds
      key: default_db
    TASK_DATABASE_USERNAME: searchworkflow
    TASK_DATABASE_PASSWORD:
      secret: true
      name: dbpasswords
      key: searchworkflow
    TASK_DATABASE_PORT:
      secret: true
      name: asl-dev-workflow-rds
      key: port
