pipeline:

  test:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm install
      - npm test
    when:
      event: [push, pull_request, tag]

  functionaltest:
    image: node:8
    commands:
      - npm run test:functional:ci -- --host selenium --baseUrl http://functionaltest:3456
    when:
      event: [push, pull_request, tag]
    secrets:
      - npm_auth_token

  publish:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: tag

matrix:
  NPM_AUTH_USERNAME:
    - asl


services:
  selenium:
    image: selenium/standalone-chrome
    when:
      event: [push, pull_request, tag]
