name: asl-components

on:
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/asl-components.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/asl-components.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22.14.0'
  MODULE: packages/asl-components
  WORKSPACE: '@ukhomeoffice/asl-components'
  # Add registry URLs as environment variables
  NPM_REGISTRY: 'https://artifactory.digital.homeoffice.gov.uk/artifactory/api/npm/npm-virtual/'
  GITHUB_REGISTRY: 'https://npm.pkg.github.com'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          # Cache npm dependencies
          cache: 'npm'
          # Set default registry (will be overridden by explicit config)
          registry-url: ${{ env.NPM_REGISTRY }}

      - name: Configure npm registries
        run: |
          # Configure Artifactory
          npm config set @asl:registry ${{ env.NPM_REGISTRY }}
          npm config set //artifactory.digital.homeoffice.gov.uk/artifactory/api/npm/npm-virtual/:_authToken ${{ secrets.ART_AUTH_TOKEN }}
          npm config set //artifactory.digital.homeoffice.gov.uk/artifactory/api/npm/npm-virtual/:always-auth=true

          # Configure GitHub Packages
          npm config set @ukhomeoffice:registry ${{ env.GITHUB_REGISTRY }}
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_AUTH_TOKEN }}

          # Increase timeout and retries
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 30000
          npm config set fetch-retry-maxtimeout 180000

      - name: Changeset
        id: changeset
        uses: ./.github/actions/changeset
        with:
          module: ${{ env.MODULE }}

      - name: Install dependencies with retries
        if: ${{ steps.changeset.outputs.changed }}
        env:
          ART_AUTH_TOKEN: ${{ secrets.ART_AUTH_TOKEN }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
        run: |
          n=0
          until [ "$n" -ge 3 ]
          do
            npm ci -w ${{ env.WORKSPACE }} --verbose && break
            n=$((n+1))
            echo "Attempt $n failed. Retrying in 10 seconds..."
            sleep 10
          done
          if [ "$n" -eq 3 ]; then exit 1; fi

      - name: Run tests
        if: ${{ steps.changeset.outputs.changed }}
        run: npm run -w ${{ env.WORKSPACE }} test
