name: asl-components

on:
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/asl-components.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/asl-components.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22.14.0'
  MODULE: packages/asl-components
  WORKSPACE: '@ukhomeoffice/asl-components'
  NPM_REGISTRY: 'https://artifactory.digital.homeoffice.gov.uk/artifactory/api/npm/npm-virtual/'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure .npmrc (Drone-style)
        run: |
          cat << EOF > .npmrc
          registry=https://registry.npmjs.org/
          @asl:registry=${{ env.NPM_REGISTRY }}
          //artifactory.digital.homeoffice.gov.uk/artifactory/api/npm/npm-virtual/:_authToken=${{ secrets.ART_AUTH_TOKEN }}
          @ukhomeoffice:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{ secrets.GH_AUTH_TOKEN }}
          fetch-retries=5
          fetch-retry-mintimeout=30000
          EOF

      - name: Pre-flight Artifactory check
        run: |
          # Test connection with shorter timeout
          if ! curl -s -m 15 -I ${{ env.NPM_REGISTRY }}; then
            echo "::warning::Artifactory unreachable, falling back to public registry"
            npm config set @asl:registry https://registry.npmjs.org/
          fi

      - name: Install with retries
        if: ${{ steps.changeset.outputs.changed }}
        run: |
          n=0
          until [ "$n" -ge 3 ]; do
            npm ci -w ${{ env.WORKSPACE }} --verbose && break
            n=$((n+1))
            sleep $((n*5))
          done
          [ "$n" -lt 3 ] || exit 1

      - name: Run tests
        if: ${{ steps.changeset.outputs.changed }}
        run: npm run -w ${{ env.WORKSPACE }} test
