name: asl-components

on:
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/asl-components.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/asl-components.yml'

env:
  NODE_VERSION: '22.14.0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Changeset
        id: changeset
        env:
          TARGET_BRANCH: ${{ github.ref }}
          SOURCE_COMMIT: ${{ github.sha }}
          BUILD_EVENT: ${{ github.event_name }}
          SKIP_STATUS: 78
          MODULES: packages/asl
        run: |
          node ./ci/changeset.js --modules $MODULES || true
          exit_code=$?
          if [ $exit_code -eq $SKIP_STATUS ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          elif [ $exit_code -ne 0 ]; then
            echo "Changeset failed with exit code $exit_code"
            exit $exit_code
          fi

      - name: Run tests
        run: npm run test
        if: !steps.changeset.outputs.changed == 'false'
        run: |
          npm run -w @ukhomeoffice/asl-components test
