name: aspel-workspace

on:
  pull_request:
    paths:
      - 'ci/**'
      - '.github/workflows/aspel-workspace.yml'
  push:
    branches:
      - main
    paths:
      - 'ci/**'
      - '.github/workflows/aspel-workspace.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22.14.0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        env:
          ART_AUTH_TOKEN: ${{ secrets.ART_AUTH_TOKEN }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
        run: npm ci --workspaces=false

      - name: Test
        run: npm run test:mono
