pipeline:

  npm_auth:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - echo "_authToken=$${NPM_AUTH_TOKEN}" >> .npmrc
    when:
      event: [push, pull_request]

  test:
    image: node:8
    commands:
      - npm install
      - npm test
    when:
      event: [push, pull_request]

  compile:
    image: node:8
    commands:
      - npm run build
    when:
      event: [push, pull_request]

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t asl .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl quay.io/ukhomeofficedigital/asl-inspector-ui:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-inspector-ui:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_dev_deploy:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/asl-deploy-bot
    branch: master
    secrets:
      - drone_token
    params: REPO=${DRONE_REPO},PLUGIN_NUMBER=${DRONE_BUILD_NUMBER}
    deploy_to: dev
    when:
      branch: master
      event: push

  configure_deploy:
    image: node:8
    commands:
      - npm install -g kube-cookbook
      - cd ./deploy
      - kube-cookbook ./.kube.yaml
      - kube-cookbook ./.redis.yaml
    when:
      environment: dev
      event: deployment

  dev_deploy:
    image: quay.io/ukhomeofficedigital/kd:v0.5.0
    secrets:
      - kube_server
      - kube_token
    commands:
      - ./deploy/deploy.sh
    when:
      environment: dev
      event: deployment
